openapi: 3.0.0
info:
  title: Combined User and Slide Management API
  description: API endpoint for slides
  version: 1.0.0
servers:
  - url: http://localhost:5000  # Update with your API's base URL
paths:
  /api/slides:
    get:
      summary: Get a list of all slides
      responses:
        '200':
          description: A list of all slides
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Slide'
        '404':
          description: Departments not found
    post:
      summary: Create a new slide
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SlideInput'
      responses:
        '201':
          description: Slide created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Slide'
        '400':
          description: Slide NOT created
  /api/slides/{slide_title}:
    get:
      summary: Get details of a specific slide by title
      parameters:
        - in: path
          name: slide_title
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Slide details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Slide'
        '404':
          description: Slide not found
    patch:
      summary: Update a specific slide by title (partial update)
      parameters:
        - in: path
          name: slide_title
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SlideInput'
      responses:
        '200':
          description: Slide updated
        '400':
          description: Slide not found or invalid data
    put:
      summary: Update a specific slide by title (full update)
      parameters:
        - in: path
          name: slide_title
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SlideInput'
      responses:
        '200':
          description: Slide updated
        '400':
          description: Slide not found or invalid data
    delete:
      summary: Delete a slide by title
      parameters:
        - in: path
          name: slide_title
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Slide deleted
        '404':
          description: Slide not found
components:
  schemas:
    Slide:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
          required: true  # Marked as required
        content:
          type: string
          required: true  # Marked as required
        content_type:
          type: string
          required: true  # Marked as required
        image_url:
          type: string
        video_url:
          type: string
        author_id:
          type: string
          required: true  # Marked as required
        departments:
          type: array
          items:
            type: string
    SlideInput:
      type: object
      properties:
        title:
          type: string
          required: true  # Marked as required
        content:
          type: string
          required: true  # Marked as required
        content_type:
          type: string
          required: true  # Marked as required
        author_id:
          type: string
          required: true  # Marked as required
        image_url:
          type: string
        video_url:
          type: string
        departments:
          type: array
          items:
            type: string
